# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - githubactions2022

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4ea9729c98a43aea20c9d635c544c2f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_327b157fd7fa4e83b8155a892c72e747 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4ea9729c98a43aea20c9d635c544c2f }}/WeatherApi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'githubactions2022'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f67b4d8494d747309442ba41e697f546 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4ea9729c98a43aea20c9d635c544c2f }}/WeatherApi:${{ github.sha }}'